#!/usr/bin/env bash
# import_baselines.sh — (re)create the vendored baseline modules from the authors' published
# repository. The result is already committed in src/; run this only to reproduce it.
#
#   Source: https://github.com/Letronghien/ao-am-pm-qm-sa  (pinned commit)
#     aomdv/   AOMDV (port of the ns-2.35 code, Marina & Das)       -> src/aomdv  (unchanged)
#     mpaodv/  PMAODV [4] and QMAODV [5]                             -> src/mpaodv (see below)
#
# src/mpaodv is the published module with the code of a separate self-adaptive variant removed
# (tools/strip_sa.py): only options that are switched off for PMAODV and QMAODV are deleted, so
# PMAODV and QMAODV behave exactly as published. `make verify-baseline` checks this by running
# the unmodified module side by side (bit-identical results required).
#
#   FORCE=1 bash tools/import_baselines.sh
set -euo pipefail
REPO=$(cd "$(dirname "$0")/.." && pwd)
URL=${URL:-https://github.com/Letronghien/ao-am-pm-qm-sa.git}
COMMIT=${COMMIT:-56d143cd2c27bfd9a653495ffa247c9ab23716ba}
FORCE=${FORCE:-0}
if [[ -f "$REPO/src/mpaodv/CMakeLists.txt" && -f "$REPO/src/aomdv/CMakeLists.txt" && "$FORCE" != 1 ]]; then
  echo "baselines already vendored in src/ (FORCE=1 to recreate)"; exit 0
fi
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
git clone -q "$URL" "$TMP/src"; git -C "$TMP/src" checkout -q "$COMMIT"
REV=$(git -C "$TMP/src" rev-parse HEAD)
rm -rf "$REPO/src/aomdv" "$REPO/src/mpaodv"
cp -a "$TMP/src/aomdv" "$REPO/src/aomdv"
cp -a "$TMP/src/mpaodv" "$REPO/src/mpaodv"
python3 "$REPO/tools/strip_sa.py" "$REPO/src/mpaodv" mpaodv
for old in pmaodv qmaodv; do
  [[ -d "$REPO/src/$old" ]] && { (cd "$REPO" && git rm -rq "src/$old" 2>/dev/null) || rm -rf "$REPO/src/$old"; }
done
{
  echo "# Baseline provenance — generated by tools/import_baselines.sh"
  echo "source: $URL"
  echo "commit: $REV"
  echo "date:   $(date -Iseconds)"
  echo
  echo "| Protocol | Module / helper | Reference |"
  echo "|---|---|---|"
  echo "| AOMDV | aomdv / AomdvHelper (unchanged) | Marina & Das, ICNP 2001 (ns-2.35 port) |"
  echo "| PMAODV | mpaodv / PmaodvHelper(k) | Le et al., LNNS 1782, Springer, 2026, pp. 287-299 |"
  echo "| QMAODV | mpaodv / QmaodvHelper | Le et al., LNDECT 281, Springer, 2026, pp. 147-162 |"
  echo
  echo "src/mpaodv = published module processed by tools/strip_sa.py (removes options that are"
  echo "off for PMAODV/QMAODV); identity of PMAODV/QMAODV results is checked by make verify-baseline."
  for m in aomdv mpaodv; do
    echo; echo "## $m (sha256)"; echo '```'
    (cd "$REPO/src/$m" && find . -type f \( -name '*.cc' -o -name '*.h' -o -name CMakeLists.txt \) | sort | xargs -r sha256sum)
    echo '```'
  done
} > "$REPO/docs/BASELINE_PROVENANCE.md"
echo "baselines vendored from ${REV:0:12}; provenance -> docs/BASELINE_PROVENANCE.md"
