#!/usr/bin/env bash
# import_baselines.sh — copy PMAODV, QMAODV and EVERY non-standard module they depend on
# (e.g. aomdv) from a working ns-3.48 tree into this repo, and record provenance.
#
#   bash tools/import_baselines.sh                          # source: ~/nbqmaodv-fanet/ns-3-nbq/src
#   FORCE=1 bash tools/import_baselines.sh                  # re-import (overwrite)
#   BASE_SRC=/other/ns-3.48/src bash tools/import_baselines.sh
#
# Dependencies are found in three places of each module:
#   * CMakeLists.txt  LIBRARIES_TO_LINK ${libXXX}
#   * relative includes  "../../XXX/model/..."
#   * includes  "ns3/XXX-module.h" / "ns3/XXX-....h" whose module folder exists in BASE_SRC
# Modules shipped with ns-3.48 are never copied. The source tree is only READ.
set -euo pipefail
REPO=$(cd "$(dirname "$0")/.." && pwd)
BASE_SRC=${BASE_SRC:-$HOME/nbqmaodv-fanet/ns-3-nbq/src}
FORCE=${FORCE:-0}
ROOTS=${ROOTS:-"pmaodv qmaodv"}

STOCK="antenna aodv applications bridge brite buildings click config-store core csma csma-layout dsdv dsr
energy fd-net-device flow-monitor internet internet-apps lr-wpan lte mesh mobility mpi netanim network
nix-vector-routing olsr openflow point-to-point point-to-point-layout propagation sixlowpan spectrum stats
tap-bridge test topology-read traffic-control uan virtual-net-device visualizer wifi zigbee"

# ---- resolve the dependency closure --------------------------------------------------
MODS=$(BASE_SRC="$BASE_SRC" ROOTS="$ROOTS" STOCK="$STOCK" python3 - <<'PY'
import os, re, sys
base = os.environ["BASE_SRC"]; stock = set(os.environ["STOCK"].split())
todo = os.environ["ROOTS"].split(); seen = []
local = {d for d in os.listdir(base) if os.path.isfile(os.path.join(base, d, "CMakeLists.txt"))}
while todo:
    m = todo.pop(0)
    if m in seen: continue
    if m not in local:
        sys.exit(f"ERROR: module '{m}' not found in {base}")
    seen.append(m)
    deps = set()
    cm = open(os.path.join(base, m, "CMakeLists.txt")).read()
    deps |= set(re.findall(r"\$\{lib([A-Za-z0-9_-]+)\}", cm))
    for root, _, files in os.walk(os.path.join(base, m)):
        if "/build" in root: continue
        for f in files:
            if not f.endswith((".h", ".cc")): continue
            txt = open(os.path.join(root, f), errors="ignore").read()
            deps |= {d for d in re.findall(r'#include\s+"(?:\.\./){2,}([A-Za-z0-9_-]+)/', txt) if d not in ("model", "helper", "utils", "test")}
            for inc in re.findall(r'#include\s+"ns3/([A-Za-z0-9_-]+)\.h"', txt):
                for cand in local:          # ns3/aomdv-routing-protocol.h -> aomdv
                    if inc == f"{cand}-module" or inc.startswith(cand + "-"):
                        deps.add(cand)
    for d in sorted(deps):
        if d == m or d in stock or d in seen: continue
        if d in local: todo.append(d)
        else: print(f"WARNING: {m} needs '{d}', which is neither stock ns-3 nor in {base}", file=sys.stderr)
print(" ".join(seen))
PY
)
echo "modules to import (with dependencies): $MODS"

IMPORTED=0
for m in $MODS; do
  if [[ -f "$REPO/src/$m/CMakeLists.txt" && "$FORCE" != 1 ]]; then
    echo "  src/$m already present (FORCE=1 to overwrite)"; continue
  fi
  IMPORTED=1
  rm -rf "$REPO/src/$m"
  cp -a "$BASE_SRC/$m" "$REPO/src/$m"
  find "$REPO/src/$m" \( -name build -type d -prune -o -name '*.bak*' -o -name '*.orig' \) -exec rm -rf {} + 2>/dev/null || true
  echo "  imported src/$m  <-  $BASE_SRC/$m"
done

# keep the existing provenance (incl. include-guard renames) if nothing was (re)imported
if [[ "$IMPORTED" == 0 && -f "$REPO/docs/BASELINE_PROVENANCE.md" ]]; then
  echo "provenance unchanged"; exit 0
fi
{
  echo "# Baseline provenance — generated by tools/import_baselines.sh"
  echo "source:  $BASE_SRC"
  echo "modules: $MODS"
  echo "date:    $(date -Iseconds)"
  echo "host:    $(hostname)"
  for m in $MODS; do
    echo; echo "## $m"
    (cd "$REPO/src/$m" && find . -type f \( -name '*.cc' -o -name '*.h' -o -name CMakeLists.txt \) | sort | xargs -r sha256sum)
  done
} > "$REPO/docs/BASELINE_PROVENANCE.md"
echo "provenance -> docs/BASELINE_PROVENANCE.md"
